### ISSUE TITLE
dada2 Error: Can't find files for block a expected files such as

### ISSUE THREAD

**Issue by sarah872** [hildebra/lotus2#21]
I am trying lotus on a set of simulated reads. For this, I have a fasta with my sequences (fragment of 16S, depending on the primer pair), that I use to simulate reads:

```
for file in *fa; do art_illumina -amp -p -l 250 -f 500 -ss MSv3 -i $file -o $(basename $file .fa). -m 300 -s 10; done && rm *aln && pigz *fq
```

My mapping file looks like this:
```
#SampleID	fastqFile	ForwardPrimer	ReversePrimer
314F-806R	314F-806R.1.fq.gz,314F-806R.2.fq.gz	CCTAYGGGRBGCASCAG	GGACTACNNGGGTATCTAAT
515F-806R	515F-806R.1.fq.gz,515F-806R.2.fq.gz	GTGCCAGCMGCCGCGGTAA	GGACTACNNGGGTATCTAAT
515F-907R	515F-907R.1.fq.gz,515F-907R.2.fq.gz	GTGCCAGCMGCCGCGGTAA	CCGTCAATTCCTTTGAGTTT
799F-1193R	799F-1193R.1.fq.gz,799F-1193R.2.fq.gz	AACMGGATTAGATACCCKG	ACGTCATCCCCACCTTCC
```

And I am running lotus as
```
./lotus2/lotus2 -i . -m map.txt -o mytest -amplicon_type SSU -CL dada2 -refDB SLV
```
However, I am getting the following error in the dada2 step;
```
SampleID	Barcode	Instances
314F-806R		2
515F-806R		17
515F-907R		21
799F-1193R		17
Time taken: : 502ms
Error: Can't find files for block a expected files such as


Aborting dada2 run
Execution halted
```

Running it without dada2 works fine:

```
./lotus2/lotus2 -i . -m map.txt -o mytest
./lotus2/lotus2 -i . -m map.txt -o mytest2 -amplicon_type SSU -refDB SLV
```

**Comment by hildebra** [comment]
Hey Sarah, my first guess would be that this is related to the sample names: "314F-806R" would probably be changed to "314F.806R" in R? It's just a guess but can you try this, then I could try to adress this bug (although this sample name might cause problems in any case, if you have file names with a -  character). best,
Falk

**Comment by ZhangDengwei** [comment]
I also encountered the same issue, with the command below

`lotus2 -i /data3/zhangdw/03.Project/19.ACC_16S/01.Raw_data/00.RawData_demultiplex -o out_lambda_dada2  -m mymap.txt -amplicon_type SSU -forwardPrimer GTGCCAGCMGCCGCGGTAA -reversePrimer GGACTACHVGGGTWTCTAAT -refDB SLV -taxAligner lambda -CL dada2 -thr 12`

Error log looks like

 ```
 -With rev Primer remaining (<= 0 mismatches) :           0; 0
  -Barcode unidentified (max 0 errors) :                   0

SampleID        Barcode Instances
SMPL0           0
SMPL1           0
SMPL10          0
SMPL11          0
SMPL12          0
SMPL13          0
SMPL14          0
SMPL15          0
SMPL16          0
SMPL17          0
SMPL18          0
SMPL19          0
SMPL2           0
SMPL20          0
SMPL21          0
SMPL22          0
SMPL23          0
SMPL24          0
SMPL25          0
SMPL26          0
SMPL27          0
SMPL3           0
SMPL4           0
SMPL5           0
SMPL6           0
SMPL7           0
SMPL8           0
SMPL9           0
Time taken: : 15s 847ms
Error: Can't find files for block a expected files such as 


Aborting dada2 run
Execution halted
```
This issue is not caused by the sample name. Can you help give some suggestions?

**Comment by hildebra** [comment]
Dear Zhang,
I think this is a different error. In this case DADA2 doesn't even start, because there are no reads to cluster. It seems to me that the read filter (sdm), is removing all reads, filtering these or maybe not finding the corresponding barcodes. Could you please post the complete sdm output? (found in [outdir]/LotuSLogS/demulti.log)

**Comment by ZhangDengwei** [comment]
[demulti.log](https://github.com/hildebra/lotus2/files/11195144/demulti.log)

Here is the file. I did not make any changes to it when running `lotus2`.

**Comment by hildebra** [comment]
Hey Zhang,
looking at the file, the problem is that all sequences get filtered out based on a)
  < min Sequence length (200)  :                275,944; 277,904
and b)
       -after Quality trimming :           263,023; 270,628
that leaves only very few remaining sequences after quality filtering, the rest gets then filtered out on various other statistics:
 > (8) homo-nt run  :                     5,727; 891
  > (0) amb. Bases  :                      362; 499
  > (2.7) binomial est. errors :           152,945; 0
so no reads are accepted:
Accepted (High qual): 0; 1,964,109 (41,554; 45,562 end-trimmed)
Accepted (Mid qual): 1,808,425;0


So the initial read  qual filtering is too harsh, this can be adapted in the sdm_opt file.
However, the numbers don't really match up, and that is all reads get accepted as mid qual, and not as high qual.
Could you send me your sdm_opt.txt file you were using for this run?
