### ISSUE TITLE
option for hashed OTU ids

### ISSUE THREAD

**Issue by kingtom2016** [hildebra/lotus2#27]
Providing option for hashed OTU ids may help integrate ASV/OTU tables from different studies or datasets.

**Comment by hildebra** [comment]
Hey kingtom2016, in general I think it is not a good idea to merge different datasets after OTU/ASV clustering. This is because quality filtering steps as well as clustering algorithms use information of sequences from a different OTU/ASV. Hence my recommendation would be to run all datasets together, LotuS2 should be fast enough for this.

**Comment by kingtom2016** [comment]
I used DADA2 to generage ASV (theoretically generate same ASV sequences among differents batches). Would this be also affected when integrating ASV tables from different batches? DADA2

**Comment by hildebra** [comment]
theoretically, practically it is not that good in my experience. you always want to cluster as many sequences as possible in the same clustering step.
Further the qual filtering step is important, dada2 (and other pipelines, like lotus2) will remove sequences that are not appearing at least X times in the dataset (see derepMin parameter)

**Comment by kingtom2016** [comment]
Thanks for your answer :)
