### ISSUE TITLE
blast output

### ISSUE THREAD

**Issue by johnrandallia** [hildebra/lotus2#60]
I would like to use the blast output in MEGAN, but the conversion from blast to rma fails.
The blast output should be tab separated and with 12 columns. I get 11 columns (without bitscore) from Lotus2?

**Comment by johnrandallia** [comment]
The 11. Column seems kind of odd as well? If I use a dummy value for the 12. column it still doesn't assign any taxonomy to the results. Only if I replace the 11. column with e.g. "0.0" it seems to get it right.

**Comment by hildebra** [comment]
Hey John,
lotus2 uses custom output columns, it's not a m8 format. These are defined as:
'qseqid sseqid pident length mismatch gapopen qstart qend sstart send qlen'
You can always check the extact mapping parameters used by looking in "LotuSLogS/LotuS_cmds.log" for the mapping command, e.g. lambda3 by default.
you can also rerun the lambda command with your required output format as arguments to lambda, but since a lot of temp files will be deleted after lotus2 is finished this will probably not work after a lotus2 run. Instead, you would want to abort lotus2 *while* it is executing the alignment, and then replace the lambda command with your own version of it (and run it).
hth,
Falk
